# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smap', '0004_sumari_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumari',
            name='icon',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
