# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smap', '0003_auto_20170115_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumari',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
