# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smap', '0004_sumari_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumari',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
